apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}
    component: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      component: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/part-of: {{ .Values.name }}
        component: {{ .Values.name }}
    spec:
      containers:
      - command:
          - "/otelcol-contrib"
          - "--config=/conf/otel-agent-config.yaml"
        image: {{ .Values.otel.image }}
        name: {{ .Values.name }}
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 4317 # Default OpenTelemetry receiver port.
        - containerPort: 8888  # Metrics.
        volumeMounts:
        - name: {{ .Values.name }}-config-vol
          mountPath: /conf
      volumes:
        - name: {{ .Values.name }}-config-vol
          configMap:
            name: {{ .Values.name }}-config
            items:
              - key: {{ .Values.name }}-config
                path: otel-agent-config.yaml
