---
apiVersion: v1
kind: Pod
metadata:
  name: adservice
  namespace: nr-host-monitoring
  labels:
    app.kubernetes.io/name: adservice
spec:
  containers:
    - name: adservice
      image: otel/demo:1.10.0-adservice
      env:
        - name: AD_SERVICE_PORT
          value: "8080"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(HOST_IP):4318
        - name: OTEL_SERVICE_NAME
          value: adservice
      ports:
        - containerPort: 8080
