version: "3"
services:
  app:
    build: ./
    environment:
      LOGGING_SCENARIO: ${LOGGING_SCENARIO}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
      SERVICE_NAME: "logs-in-context-example"
    ports:
      - "8080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:8006
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.27.0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    entrypoint: ["/otelcontribcol"]
    command: ["--config", "/otel-config.yaml"]
    environment:
      LOG_EXPORTER_LOG_LEVEL: "DEBUG"
      NEW_RELIC_API_KEY: "${NEW_RELIC_API_KEY}"
      SERVICE_NAME: "logs-in-context-example"
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "13133:13133" # health_check
      - "8006:8006" # Fluentd forward receiver
      - "8006:8006/udp" # Fluentd forward receiver
