apiVersion: v1
kind: Secret
metadata:
  name: nr-redis-secret
  namespace: nr-redis
stringData:
  # New Relic API key to authenticate the export requests.
  # docs: https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#license-key
  NEW_RELIC_API_KEY: 380d7b11e56fa29a3aa0113884483474FFFFNRAL
