version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.25.0
    volumes:
    - ./otel-config.yaml:/otel-config.yaml
    entrypoint: ["/otelcontribcol"]
    command: ["--config", "/otel-config.yaml"]
    environment:
      LOG_EXPORTER_LOG_LEVEL: "DEBUG"
      NEW_RELIC_API_KEY: "${NEW_RELIC_API_KEY}"
    ports:
      - "4317:4317"   # grpc
      - "13133:13133" # health
