# This job runs the OTLP NewRelic Mapping application in ./java/otlp-nr-mapping.
# It will fail if behavior changes in the New Relic OTLP mapping logic. If a failure
# occurs, someone should run the application locally and commit the changes.
name: OTLP NewRelic Mapping

on:
  schedule:
    # Run every day at 15:00 UTC (10:00 am CST)
    - cron:  '0 15 * * *'

jobs:
  run-otlp-nr-mapping:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Set up JDK 11
        uses: actions/setup-java@v3.7.0
        with:
          distribution: temurin
          java-version: 11
      - name: Run OTLP NewRelic mapping application
        working-directory: java
        env:
          NEW_RELIC_USER_API_KEY: ${{ secrets.NEW_RELIC_USER_API_KEY }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          INGEST_WAIT_SECONDS: 60
        run: ./gradlew :otlp-nr-mapping:run
      - name: Detect changes
        run: |
          [[ -z $(git status --porcelain) ]] && echo "Success! No changes detected." || (echo "Failure. Changes detected:"; git diff; exit 1)

